import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"
        suppressHydrationWarning={true} 
      >
        <div className="flex justify-end ">
          <Sidebar/>
          <div className="bg- amber-400"
            style={{width: "calc(100% - 17.9999%)"}}
          >
            <Header/>
            <main className="pt-12">
              <div className="min-h-[calc(100vh-91px)] py-3.5 px-0">
                {children}
              </div>
              <Footer/>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
